// <auto-generated />

using ClassLibrary.Data;

using Microsoft.EntityFrameworkCore;

using Microsoft.EntityFrameworkCore.Infrastructure;

using Microsoft.EntityFrameworkCore.Metadata;

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;



#nullable disable



namespace ClassLibrary.Migrations

{

    [DbContext(typeof(AplicationDbContext))]

    partial class AplicationDbContextModelSnapshot : ModelSnapshot

    {

        protected override void BuildModel(ModelBuilder modelBuilder)

        {

#pragma warning disable 612, 618

            modelBuilder

                .HasAnnotation("ProductVersion", "9.0.9")

                .HasAnnotation("Relational:MaxIdentifierLength", 128);



            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);



            modelBuilder.Entity("ClassLibrary.Models.Departamento", b =>

            {

                b.Property<int>("Id")

                    .ValueGeneratedOnAdd()

                    .HasColumnType("int");



                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));



                b.Property<string>("Descripcion")

                    .IsRequired()

                    .HasColumnType("nvarchar(max)");



                b.Property<string>("Nombre")

                    .IsRequired()

                    .HasColumnType("nvarchar(max)");



                b.HasKey("Id");



                b.ToTable("departamentos");

            });



            modelBuilder.Entity("ClassLibrary.Models.Empleado", b =>

            {

                b.Property<int>("Id")

                    .ValueGeneratedOnAdd()

                    .HasColumnType("int");



                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));



                b.Property<int>("DepartamentoId")

                    .HasColumnType("int");



                b.Property<string>("Email")

                    .IsRequired()

                    .HasColumnType("nvarchar(max)");



                b.Property<string>("Nombre")

                    .IsRequired()

                    .HasColumnType("nvarchar(max)");



                b.Property<int>("Salario")

                    .HasColumnType("int");



                b.HasKey("Id");



                b.HasIndex("DepartamentoId");



                b.ToTable("empleados");

            });



            modelBuilder.Entity("ClassLibrary.Models.Empleado", b =>

            {

                b.HasOne("ClassLibrary.Models.Departamento", "Departamento")

                    .WithMany()

                    .HasForeignKey("DepartamentoId")

                    .OnDelete(DeleteBehavior.Cascade)

                    .IsRequired();



                b.Navigation("Departamento");

            });

#pragma warning restore 612, 618

        }

    }

}